--- 
- 
  become: true
  become_user: bimat
  hosts: FRX4
  tasks: 
    - 
      apt: "update_cache=yes force_apt_get=yes cache_valid_time=3600"
      name: "Update apt repo and cache on all Ubuntu boxes"
    - 
      apt: "upgrade=dist force_apt_get=yes"
      name: "Upgrade all packages on servers"
    - 
      name: "Check if a reboot is needed on all servers"
      register: reboot_required_file
      stat: "path=/var/run/reboot-required get_md5=no"
    - 
      name: "Reboot the box if kernel updated"
      reboot: 
        connect_timeout: 5
        msg: "Reboot initiated by Ansible for kernel updates"
        post_reboot_delay: 30
        pre_reboot_delay: 0
        reboot_timeout: 300
        test_command: uptime
      when: reboot_required_file.stat.exists
